/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_javacallc_JNI */

#ifndef _Included_com_example_javacallc_JNI
#define _Included_com_example_javacallc_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_javacallc_JNI
 * Method:    sayhello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_javacallc_JNI_sayhello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
